---
root: true
parser: vue-eslint-parser
parserOptions:
    parser: babel-eslint
env:
    node: true
extends: 
  - eslint:recommended
  - plugin:vue/vue3-essential
  - prettier
plugins:
  - "vue"
rules: 
  "no-console": warn
  "no-debugger": warn
