version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: frontend_container
    ports:
      - 80:80
    networks: 
      app_net:
        ipv4_address: 192.168.0.2
    environment:
      TZ: "Asia/Tokyo"
      URI_BACKEND: "http://192.168.0.3:1323/api"       
    depends_on: 
        - backend
        
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: backend_container
    ports:
      - 1323:1323  # to debug
    networks: 
      app_net:
        ipv4_address: 192.168.0.3
    environment:
      TZ: "Asia/Tokyo"
      URI_FRONTEND: "http://192.168.0.2:8080"
      MYSQL_USER: trip
      MYSQL_PASSWORD: trip_app
      MYSQL_HOST: 192.168.0.4
      MYSQL_PORT: 3306
      MYSQL_DATABASE: trip_db
    depends_on: 
      - db

  db:
    image: mysql
    ports:
      - 3306:3306
    networks: 
      app_net:
        ipv4_address: 192.168.0.4
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./backend/db/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: trip_app
      MYSQL_DATABASE: trip_db
      MYSQL_USER: trip
      MYSQL_PASSWORD: trip_app
      TZ: "Asia/Tokyo"



networks: 
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
