openapi: 3.0.0
info:
  title: supporterz_hackathon_2021 API Document
  description: <b>バックエンド API仕様</b><br>
  version: '1.0'
  contact:
    name: Takeshi Haga
    email: ritorut18@gmail.com
servers:
  - url: 'http://localhost:1323'
tags:
  - name: setting
    description: 設定事項の出力
  - name: trip
    description: GPS情報抽出
paths:
  /setting/get:
    get:
      tags:
        - setting
      summary: 設定取得API
      description: |
        設定事項の出力<br>
        TODO: 設定をDBに保存し動的に変えられるようにする
      operationId: get-settings
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SettingGetResponse'
      parameters: []
  /trip/save:
    post:
      tags:
        - trip
      summary: 旅情報保存API
      description: |
        アップロードされた写真を保存するAPI<br>
      operationId: trip-save
      requestBody:
        description: Request Body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TripSaveRequest'
        required: true
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TripSaveResponse'
      x-codegen-request-body-name: body
  /trip/get:
    post:
      tags:
        - trip
      summary: 旅情報取得API
      description: |
        userIDから保存済みの旅一覧を取得するAPI
      operationId: trip-get
      requestBody:
        description: Request Body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TripGetRequest'
        required: true
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TripGetResponse'
      x-codegen-request-body-name: body
  /static/{img_url}:
    get:
      tags:
        - trip
      summary: 画像のファイルサーバAPI
      description: |
        S3に保存した画像を取得するAPI
      parameters:
      - in: path
        name: img_url
        schema:
          type: string
        description: S3に保存した画像のURL 
        required: true
      operationId: imgs-get 
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TripGetResponse'
      x-codegen-request-body-name: body

components:
  schemas:
    SettingGetResponse:
      type: object
      properties:
        gachaCoinConsumption:
          type: integer
          description: ガチャ1回あたりのコイン消費数
    TripSaveRequest:
      type: object
      properties:
        userID:
          type: string
          description: ユーザID
        imgs:
          type: object
          description: 画像
    TripSaveResponse:
      type: object
      properties:
        tripID:
          type: string
          description: 旅ごとに固有のID
    TripGetRequest:
      type: object
      properties:
        userID:
          type: string
          description: ユーザID
    TripGetResponse:
      type: object
      properties:
        tripID:
          type: array
          description: 旅IDのリスト
