# dbの作成
version: "3"

services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: backend_container
    ports:
      - 1323:1323
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_USER: trip
      MYSQL_PASSWORD: trip_app
      MYSQL_HOST: 192.168.0.4
      MYSQL_PORT: 3306
      MYSQL_DATABASE: trip_db
    depends_on: 
        - db
    networks: 
      app_net:
        ipv4_address: 192.168.0.3
    
  db:
    image: mysql
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: trip_app
      MYSQL_DATABASE: trip_db
      MYSQL_USER: trip
      MYSQL_PASSWORD: trip_app
      TZ: "Asia/Tokyo"
    platform: linux/amd64
    networks: 
      app_net:
        ipv4_address: 192.168.0.4


networks: 
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
    